analysis/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'analysis'
urlpatterns = [
    path('', views.upload, name='upload'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

analysis/models.py
from django.db import models


class FileUpload(models.Model):
    content = models.FileField(upload_to="")

analysis/forms.py
from django import forms
from .models import FileUpload


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = FileUpload
        fields = ('content', )

analysis/views.py
from django.shortcuts import render, redirect
from .forms import UploadFileForm
from django.conf import settings
from django.utils import timezone


def save(file):
    with open(f'../talk/{file}', 'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)


def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['content']
            save(file)
            return render(request, 'analysis/report.html', {'file': file})
    else:
        form = UploadFileForm()

    return render(request, 'analysis/upload.html', {'form': form})

templates/analysis/report.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<h1>Result!</h1>
<p>123</p>
<script>
    $.ajax({
        type: "POST",
        url: 'http://127.0.0.1:8668/analysis/',
        data: {
            'file': '{{ file }}',
        },
        dataType: 'json',
        success: function(data){
            $("p").text(JSON.stringify(data))
        }
    });
</script>

{% endblock %}

templates/analysis/upload.html
{% extends "base.html" %}
{% block content %}

<form action="{% url 'analysis:upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_content">파일명: </label>
    <input type="file" name="content" id="id_content">
    <button type="submit">분석하기</button>
</form>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- pybo CSS -->
<!--    <link rel="stylesheet" type="text/css" href="{% static 'pybo/style.css' %}">-->
    <title>대화 분석</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}

</body>
</html>

templates/navbar.html
<h3>Nav bar</h3>